   web:
     build: .
     ports:
       - 8080:8080
     links:
       - mongo:mongo
   mongo:  
     image: mongo:latest
     ports:
       - 27018:27018
     volumes:
       - /data/db/mongo/products-demo:/data/db/mongo/products-demo

