   web:
     build: .
     ports:
       - 8080:8080
     links:
       - mongo
   mongo:  
     image: mongo
     ports:
       - 27018:27018
     volumes:
       - /data/db/mongo/products-demo:/data/db/mongo/products-demo

