   nginx:
     build: ./nginx
     links: 
       - web-node
     ports:
       - "81:81"
   web-node:
     build: ./web
     ports:
       - 3000:3000
     links:
       - db-mongo 
       - redis
   db-mongo:  
     build: ./mongo
     environment:
       MONGODB_PASS: 12345
     ports:
       - 27017:27017  
       - 28017:28017  
     volumes:
       - /data/db/mongo/products-demo:/data/db
   memcached:
     build: ./memcached
     ports:
       - 11212:11212
   redis:
     build: ./redis
     ports:
       - 6378:6378    