   nginx:
     build: nginx/
     links: 
       - web
   web-node:
     build: .
     ports:
       - 3000:3000
     links:
       - db-mongo 
   db-mongo:  
     image: mongo
     ports:
       - 27017:27017
     volumes:
       - /data/db/mongo/products-demo:/data/db/mongo/products-demo

