   web:
     build: .
     ports:
       - 8080:8080
     links:
       - db 
   db:  
     image: mongo
     ports:
       - 27017:27017
     volumes:
       - /data/db/mongo/products-demo:/data/db/mongo/products-demo

