version: '3.7'
services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web
  nginx:
    build:
      context: ./nginx
    ports:
      - "3000:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
 