   nginx:
     build: ./nginx
     links: 
       - web-node
     ports:
       - "80:80"
   web-node:
     build: ./web
     ports:
       - 3000:3000
     links:
       - db-mongo 
   db-mongo:  
     build: ./mongo
     environment:
       MONGODB_PASS: "12345"
     ports:
       - 27017:27017  
       - 27018:27017  
     volumes:
       - /data/db/mongo/products-demo:/data/db/mongo/products-demo