branch-defau:lts:
  develop:
    environment: NoderestdevEnv-env
    group_suffix: null
  master:
    environment: NoderestdevEnv-env
branch-defaults:
  develop:
    environment: NoderestdevEnv-env
    group_suffix: null
global:
  application_name: NoderestDev-env
  default_ec2_keyname: null
  default_platform: docker
  default_region: us-east-1
  profile: eb-cli
  sc: git
